# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='修改时间')),
                ('title', models.CharField(db_column='title', max_length=200, verbose_name='标题')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
                ('image', models.ImageField(db_column='image', upload_to='', verbose_name='图片')),
                ('view_count', models.IntegerField(db_column='view_count', default=0, verbose_name='浏览次数')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '发布'), (2, '归档')], db_column='status', verbose_name='状态')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='修改时间')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='名称')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='父id')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='修改时间')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='名称')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
