# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='pid',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='父id'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(db_column='sort', default=1, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='category',
            name='style',
            field=models.IntegerField(choices=[(0, '分隔符'), (1, '固定'), (2, '主要'), (3, '折叠')], db_column='style', default=0, verbose_name='呈现样式'),
        ),
    ]
